import type { PageContent, PageRoute } from "./types";

export const photoSrc = {
  hero: "/assets/photos/hero-forest-no-face.png",
  program: "/assets/photos/program-panels-no-face.png",
  walk: "/assets/photos/satoyama-walk-no-face.png",
} as const;

const commonFlow = [
  { label: "01", title: "気になる活動を選ぶ", body: "日程・場所・内容をチェック。ピンときたものでOK。" },
  { label: "02", title: "申し込む", body: "フォームで必要事項を送るだけ。持ち物リストも届くから準備もラク。" },
  { label: "03", title: "現地で体験する", body: "地域の人や同世代と一緒に、森や畑で過ごす一日が始まる。" },
];

export const pages: PageContent[] = [
  {
    route: "/",
    navLabel: "トップ",
    eyebrow: "JUON NETWORK",
    title: "この週末、森に出かけよう。",
    lead: "森づくり、農作業、地域のひとたち。週末だけで始められる、リアルな自然体験がここにある。",
    heroPhoto: "hero",
    heroPosition: "center 44%",
    primaryCta: "どんな活動があるか見る",
    secondaryCta: "はじめての人はこちら",
    introTitle: "スマホを置いて、土に触れる週末。",
    introBody:
      "JUON NETWORKは、森の手入れや農作業、地域との交流を通じて、自然を自分の目で見て感じる体験をつくっています。一人でも、友だちとでも。週末から気軽にどうぞ。",
    features: [
      { title: "週末だけでOK", body: "日帰りや1泊2日。予定の合間にサクッと参加できる。", meta: "気軽さ" },
      { title: "リアルを体感", body: "土や木の手触り、地域の人の話。画面の向こうにはない体験。", meta: "体験" },
      { title: "一人でも平気", body: "現地に行けば同世代がいる。気づいたらまた来たくなる。", meta: "仲間" },
    ],
    timelineTitle: "参加まで、たった3ステップ",
    timeline: commonFlow,
    finalTitle: "次の週末、ちょっと外へ。",
    finalBody: "まずは気になる活動をチェック。予定に「森」って入れてみるだけで、週末が変わる。",
  },
  {
    route: "/first-time",
    navLabel: "はじめて",
    eyebrow: "はじめての人へ",
    title: "はじめてでも、全然大丈夫。",
    lead: "服も持ち物も当日の流れも、ここで先にわかる。あとは行くだけ。",
    heroPhoto: "walk",
    heroPosition: "center 50%",
    primaryCta: "活動を探す",
    secondaryCta: "よくある質問を見る",
    introTitle: "不安ゼロで現地に向かおう。",
    introBody:
      "一人で行って大丈夫？体力もつ？何を着ていけば？はじめての人が気になることを先にまとめました。あとは行くだけ。",
    features: [
      { title: "一人参加、全然あり", body: "受付でスタッフが案内するし、一人で来てる人もたくさん。", meta: "ソロOK" },
      { title: "初心者ウェルカム", body: "作業前に説明があるから、できる範囲でやればOK。", meta: "未経験OK" },
      { title: "持ち物チェック", body: "服装・雨対策・必要な道具、事前に確認できる。", meta: "準備" },
    ],
    timelineTitle: "当日はこんな感じ",
    timeline: [
      { label: "集合", title: "現地で合流", body: "集合場所でスタッフが待ってる。参加者同士も自然に合流。" },
      { label: "説明", title: "やり方を聞く", body: "道具の使い方や作業の範囲をみんなで確認してからスタート。" },
      { label: "体験", title: "実際にやってみる", body: "無理しなくてOK。自分のペースで森づくりや農作業を体験。" },
    ],
    finalTitle: "迷ってるなら、聞いてみて。",
    finalBody: "申し込む前でも相談できる。小さな疑問でも気軽にどうぞ。",
  },
  {
    route: "/activities",
    navLabel: "活動を探す",
    eyebrow: "活動を探す",
    title: "自分に合うやつ、きっとある。",
    lead: "森づくり、農作業、地域交流。週末から参加できるプログラムを、やりたいことや場所から選べる。",
    heroPhoto: "program",
    heroPosition: "center 50%",
    primaryCta: "イベント日程を見る",
    secondaryCta: "はじめての人はこちら",
    introTitle: "1日体験から、通い続ける活動まで。",
    introBody:
      "興味や体力、スケジュールに合わせて選べるように、プログラムの特徴をわかりやすくまとめました。",
    features: [
      { title: "森林の楽校", body: "森の手入れを体験しながら、森と暮らしのつながりを学ぶ。", meta: "森" },
      { title: "田畑の楽校", body: "農作業を通じて、食と地域のリアルに触れる。", meta: "畑" },
      { title: "入門講座", body: "道具の使い方や安全を学んでから現地へ。安心の第一歩。", meta: "学ぶ" },
    ],
    timelineTitle: "活動の選び方",
    timeline: commonFlow,
    finalTitle: "迷ったら、初心者OKの活動から。",
    finalBody: "週末開催・初心者歓迎のプログラムから探すと、最初の一歩を踏み出しやすい。",
  },
  {
    route: "/events",
    navLabel: "イベント",
    eyebrow: "イベント日程",
    title: "次の週末、予定あいてる？",
    lead: "地域・日程・やりたいことから、参加できるイベントを見つけよう。",
    heroPhoto: "walk",
    heroPosition: "center 45%",
    primaryCta: "募集中のイベントを見る",
    secondaryCta: "活動から探す",
    introTitle: "スケジュールから選べる参加の入口。",
    introBody:
      "直近で申し込める活動を、開催地域やタイプ、初心者向けかどうかで整理しています。",
    features: [
      { title: "森で汗を流す", body: "森づくりや里山整備。木に触れる体験。", meta: "森林" },
      { title: "畑で土に触れる", body: "収穫や畑の手入れで、地域とつながる。", meta: "農作業" },
      { title: "まず話を聞く", body: "講座や説明会で、知識をつけてから参加もあり。", meta: "講座" },
    ],
    timelineTitle: "申し込みまでの流れ",
    timeline: commonFlow,
    finalTitle: "日程が合うものから始めよう。",
    finalBody: "まずは直近のイベントをチェック。予定に入れたら、あとは当日を待つだけ。",
  },
  {
    route: "/forest-school",
    navLabel: "森林の楽校",
    eyebrow: "森林の楽校",
    title: "森林の楽校",
    lead: "森の手入れを体験しながら、地域の人と交流。森と暮らしのつながりを体で学ぶプログラム。",
    heroPhoto: "hero",
    heroPosition: "center 42%",
    primaryCta: "開催予定を見る",
    secondaryCta: "はじめての人はこちら",
    introTitle: "木を植えるだけじゃない、森のリアル。",
    introBody:
      "森の状態を見て、安全に作業して、地域の人の話を聞く。体験と理解がセットになった活動。",
    features: [
      { title: "森を手入れする", body: "下草刈りや道づくり。現地で必要な作業に参加。", meta: "作業" },
      { title: "自然のしくみを知る", body: "水・土・木・暮らしがどうつながってるか、体で感じる。", meta: "学び" },
      { title: "地域の人に会う", body: "現地の人の話を聞くと、森のことが自分ごとになる。", meta: "交流" },
    ],
    timelineTitle: "一日の流れ",
    timeline: commonFlow,
    finalTitle: "森に触れる一日を予定に入れよう。",
    finalBody: "一度入った森の記憶は、自然との関わり方をじわじわ変えてくれる。",
  },
  {
    route: "/field-school",
    navLabel: "田畑の楽校",
    eyebrow: "田畑の楽校",
    title: "田畑の楽校",
    lead: "農作業を通じて、食と地域のつながりを体で学ぶ援農プログラム。",
    heroPhoto: "program",
    heroPosition: "center 48%",
    primaryCta: "開催予定を見る",
    secondaryCta: "地域の活動を見る",
    introTitle: "土に触れると、地域の暮らしが見えてくる。",
    introBody:
      "収穫、草取り、畑の手入れ。ひとつひとつの作業を通じて、食の裏側と地域の営みに触れる。",
    features: [
      { title: "農作業を体験", body: "季節に合わせた作業を、地域の人と一緒にやる。", meta: "体験" },
      { title: "地域を手伝う", body: "人手が必要な時期の現場を支えて、交流にもつながる。", meta: "応援" },
      { title: "食の裏側を知る", body: "食卓に届くまでの手間や、地域ならではの知恵を体感。", meta: "食" },
    ],
    timelineTitle: "一日の流れ",
    timeline: commonFlow,
    finalTitle: "食と地域を、体で感じよう。",
    finalBody: "農山村の時間に飛び込んで、暮らしに近い自然との関わりを見つけてほしい。",
  },
  {
    route: "/regional",
    navLabel: "地域の活動",
    eyebrow: "地域の活動",
    title: "地域の活動",
    lead: "散策、勉強会、交流イベント。近くの地域とつながるきっかけがここにある。",
    heroPhoto: "walk",
    heroPosition: "center 50%",
    primaryCta: "地域の活動を見る",
    secondaryCta: "支援のかたち",
    introTitle: "いきなり山奥じゃなくてもいい。",
    introBody:
      "森や農山村にいきなり飛び込むのはちょっと…という人も、地域活動や交流イベントからゆるく関わり始められる。",
    features: [
      { title: "里山を歩く", body: "地域の風景を歩きながら、自然と暮らしの関係を知る。", meta: "散策" },
      { title: "地域のことを学ぶ", body: "課題や活動の背景を知って、次のアクションにつなげる。", meta: "学び" },
      { title: "人とつながる", body: "参加者や地域の人との、ゆるくて続く接点ができる。", meta: "交流" },
    ],
    timelineTitle: "関わり方のステップ",
    timeline: commonFlow,
    finalTitle: "近場の活動から始めよう。",
    finalBody: "地域との距離をちょっとずつ縮める入口として、気軽に使ってほしい。",
  },
  {
    route: "/course",
    navLabel: "入門講座",
    eyebrow: "入門講座",
    title: "森林ボランティア入門講座",
    lead: "森づくりの基礎と道具の安全な使い方を、はじめての人にもわかりやすく。",
    heroPhoto: "hero",
    heroPosition: "center 38%",
    primaryCta: "講座日程を見る",
    secondaryCta: "問い合わせる",
    introTitle: "学んでから行くと、森の体験がもっと深くなる。",
    introBody:
      "安全のこと、道具のこと、森の見方、活動の選び方。知ってから参加すると、不安が減って楽しさが増す。",
    features: [
      { title: "森の基本を知る", body: "森林の役割や保全の考え方を、ゼロからわかりやすく。", meta: "基礎" },
      { title: "安全を学ぶ", body: "現地で気をつけることや、判断のポイントを押さえる。", meta: "安全" },
      { title: "道具に触れる", body: "実際に使う道具の扱い方を、手を動かして覚える。", meta: "実践" },
    ],
    timelineTitle: "講座の流れ",
    timeline: commonFlow,
    finalTitle: "基礎を固めて、森へ出発。",
    finalBody: "知ってから行くと、現地での体験がぐっと意味のある時間になる。",
  },
  {
    route: "/voices",
    navLabel: "参加者の声",
    eyebrow: "参加者の声",
    title: "行ってきた人の、リアルな声。",
    lead: "はじめての不安も、また行きたくなる理由も。森や地域で過ごした時間から生まれた言葉たち。",
    heroPhoto: "walk",
    heroPosition: "center 47%",
    primaryCta: "活動を探す",
    secondaryCta: "はじめての人はこちら",
    introTitle: "自分に近い人の体験が、最初の一歩を軽くする。",
    introBody:
      "大学生、20代社会人、リピーター。参加前と後で気持ちがどう変わったか、短いストーリーで紹介。",
    features: [
      { title: "一人で行ったけど平気だった", body: "現地で自然に会話が生まれて、次も来たいと思えた。", meta: "学生" },
      { title: "環境問題が自分ごとになった", body: "地域の人の話がリアルで、ニュースとは全然違う実感が残った。", meta: "社会人" },
      { title: "週末の過ごし方が変わった", body: "自然の中で体を動かす時間が、暮らしのリズムになった。", meta: "リピーター" },
    ],
    timelineTitle: "参加後に変わること",
    timeline: commonFlow,
    finalTitle: "あなたの最初の体験を見つけよう。",
    finalBody: "誰かの声をきっかけに、自分に合う活動をチェックしてみて。",
  },
  {
    route: "/about",
    navLabel: "JUONとは",
    eyebrow: "JUONとは",
    title: "都市と農山村をつなぎ、森を育てる。",
    lead: "自然と向き合う知恵を学び伝え、世代をこえたつながりをつくる認定NPO法人です。",
    heroPhoto: "hero",
    heroPosition: "center 45%",
    primaryCta: "活動を見る",
    secondaryCta: "支援のかたち",
    introTitle: "わたしたちがやっていること。",
    introBody:
      "森を守ること、地域とつながること、次の世代へ伝えること。活動への参加を通じて、都市と農山村の関係をつなぎ直しています。",
    features: [
      { title: "森を守る", body: "人の手が必要な森に関わって、健やかな循環を支える。", meta: "森林" },
      { title: "地域とつながる", body: "地域の課題や魅力を、現地の人との交流から学ぶ。", meta: "地域" },
      { title: "次の世代へ", body: "若い人が参加しやすい入口を整えて、続く担い手を育てる。", meta: "未来" },
    ],
    timelineTitle: "活動の広がり",
    timeline: commonFlow,
    finalTitle: "まずは活動に参加してみて。",
    finalBody: "団体を知るいちばん自然な方法は、現地で体験してみること。",
  },
  {
    route: "/support",
    navLabel: "支援する",
    eyebrow: "支援する",
    title: "森と地域を、続けて支える。",
    lead: "会員・寄付・ボランティア。自分に合うかたちで、都市と農山村をつなぐ活動を応援できる。",
    heroPhoto: "program",
    heroPosition: "center 52%",
    primaryCta: "支援のかたちを見る",
    secondaryCta: "活動に参加する",
    introTitle: "支援のかたちは、ひとつじゃない。",
    introBody:
      "会員になって継続的に支える、寄付で応援する、現地で手を動かす。自分に合う関わり方を選べます。",
    features: [
      { title: "会員になる", body: "継続的に活動を支えつつ、情報や交流の機会にもつながる。", meta: "会員" },
      { title: "寄付する", body: "一回からでも、森づくりや若者の参加機会を応援できる。", meta: "寄付" },
      { title: "活動に参加する", body: "現地で体験しながら、地域を支える力になる。", meta: "参加" },
    ],
    timelineTitle: "支援が届く先",
    timeline: commonFlow,
    finalTitle: "まず一歩、関わり方を選ぼう。",
    finalBody: "支援は重い決断じゃない。活動と地域を続けるための、参加のかたち。",
  },
  {
    route: "/faq",
    navLabel: "FAQ",
    eyebrow: "よくある質問",
    title: "気になること、まとめました。",
    lead: "はじめて参加する前に知りたいこと、ここで解消できる。",
    heroPhoto: "walk",
    heroPosition: "center 42%",
    primaryCta: "問い合わせる",
    secondaryCta: "はじめての人はこちら",
    introTitle: "申し込む前のモヤモヤ、ここで解消。",
    introBody:
      "一人で行って平気？服装は？道具いる？雨だったら？費用は？気になることをまとめました。",
    features: [
      { title: "一人でも大丈夫？", body: "大丈夫。一人参加の人も多くて、現地で自然に合流できるように案内します。", meta: "Q1" },
      { title: "初心者でも平気？", body: "もちろん。最初に説明があるし、できる範囲でやればOK。", meta: "Q2" },
      { title: "道具は必要？", body: "活動による。募集ページに持ち物と貸出情報が載ってるからチェックしてね。", meta: "Q3" },
    ],
    timelineTitle: "事前に確認しておくこと",
    timeline: commonFlow,
    finalTitle: "それでも不安なら、聞いてみて。",
    finalBody: "小さな疑問でも、問い合わせで気軽に確認できる。",
  },
  {
    route: "/contact",
    navLabel: "お問い合わせ",
    eyebrow: "問い合わせ",
    title: "聞きたいことがあれば、気軽に。",
    lead: "参加の相談、取材、連携の話など、なんでも問い合わせてOK。",
    heroPhoto: "walk",
    heroPosition: "center 52%",
    primaryCta: "問い合わせフォームへ",
    secondaryCta: "よくある質問を見る",
    introTitle: "迷ってるなら、聞いてから決めればいい。",
    introBody:
      "参加前の不安、活動内容の確認、団体との連携相談。目的に合わせて問い合わせできます。",
    features: [
      { title: "参加について聞く", body: "服装、持ち物、体力面、申し込み前の疑問を確認できる。", meta: "参加" },
      { title: "情報を受け取る", body: "毎月のイベント情報や活動レポートをメールで届けます。", meta: "メール" },
      { title: "連携・取材", body: "学校、企業、メディアからの相談窓口としても使えます。", meta: "連携" },
    ],
    timelineTitle: "問い合わせの流れ",
    timeline: commonFlow,
    finalTitle: "まずは活動をチェックしてみて。",
    finalBody: "問い合わせと一緒に、直近の活動一覧も見てみてね。",
  },
];

export const fallbackRoute: PageRoute = "/";
export const pageMap = new Map<PageRoute, PageContent>(pages.map((page) => [page.route, page]));
